### ISSUE TITLE
Build from source doesn't mention bazaar requirement

### ISSUE THREAD

**Issue by danesparza** [epeli/hooktftp#6]
Trying to build from source, it looks like this project requires "Bazaar" (bzr).  The readme should be updated to reflect that.

**Comment by sspans** [comment]
The README.md has been updated.

Please report any other inconsistencies in the documentation, 
help in making hooktftp easier to use is always welcome.

**Comment by rmedaer** [comment]
__FYI:__ I'm rewriting a part of the project. In this scope I rewrote the debian packaging and added bzr package in dependencies. (See https://github.com/rmedaer/hooktftp)
